### ISSUE TITLE
ChunkedEncodingError when download_images

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/street-view-green-view#47]
not sure what happened here?

```
(.venv) ➜  street-view-green-view git:(pr/46) python -m src.download_images data/interim/Three_Rivers_Michigan_USA_points.gpkg data/images/ThreeRivers/
Downloading 4960 Images:  53%|█████▎    | 2614/4960 [07:24<06:39,  5.88images/s]
Traceback (most recent call last):

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/urllib3/response.py", line 737, in _error_catcher
    yield

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/urllib3/response.py", line 883, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)

urllib3.exceptions.IncompleteRead: IncompleteRead(6194524 bytes read, 7596945 more expected)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/urllib3/response.py", line 1043, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/urllib3/response.py", line 963, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/urllib3/response.py", line 861, in _raw_read
    with self._error_catcher():

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/urllib3/response.py", line 761, in _error_catcher
    raise ProtocolError(arg, e) from e

urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(6194524 bytes read, 7596945 more expected)', IncompleteRead(6194524 bytes read, 7596945 more expected))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/src/download_images.py", line 177, in <module>
    app()

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/src/download_images.py", line 163, in main
    thread_map(

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/src/download_images.py", line 152, in download_image_for_gdf_row
    results = mapillary.get_image_from_coordinates(latitude, longitude)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/stamina/_core.py", line 601, in sync_inner
    for attempt in retry_ctx.with_name(  # noqa: RET503

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/stamina/_core.py", line 439, in __iter__
    for r in _t.Retrying(

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 435, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 390, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/stamina/_core.py", line 605, in sync_inner
    return wrapped(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/src/download_images.py", line 92, in get_image_from_coordinates
    results["image_path"] = self._download_image(image_url, results["image_id"])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/stamina/_core.py", line 601, in sync_inner
    for attempt in retry_ctx.with_name(  # noqa: RET503

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/stamina/_core.py", line 439, in __iter__
    for r in _t.Retrying(

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 435, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 390, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/stamina/_core.py", line 605, in sync_inner
    return wrapped(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/src/download_images.py", line 111, in _download_image
    image_content = response.content
                    ^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)

requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(6194524 bytes read, 7596945 more expected)', IncompleteRead(6194524 bytes read, 7596945 more expected))
```

**Comment by jayqi** [comment]
It seems like something interrupted the download partway through. I'm not sure if we can easily tell if it was on your end or on the server end. 

I'm not sure if this is a one-off issue that is just due to a bad connection, or if this is something more common we need to solve for. From some cursory Googling, this sort of thing seems to happen more commonly if one is doing streaming or chunked downloads, which I don't think we are doing.

https://stackoverflow.com/questions/49064398/requests-exceptions-chunkedencodingerror-connection-broken-incompleteread0

**Comment by danbjoseph** [comment]
worked the second time
```
(.venv) ➜  street-view-green-view git:(pr/46) python -m src.download_images data/interim/Three_Rivers_Michigan_USA_points.gpkg data/images/ThreeRivers/
Downloading 4960 Images:  55%|██████████▍        | 2718/4960 [07:57<05:47,  6.45images/s]stamina.retry_scheduled
Downloading 4960 Images: 100%|███████████████████| 4960/4960 [15:33<00:00,  5.31images/s]
     osm_id      highway                    geometry  ... residual image_path error
0  17967640  residential  POINT (-85.65161 41.95364)  ...     None       None  None
1  17967640  residential  POINT (-85.65155 41.95379)  ...     None       None  None
2  17967640  residential  POINT (-85.65149 41.95394)  ...     None       None  None
3  17967640  residential  POINT (-85.65142 41.95408)  ...     None       None  None
4  17964573  residential  POINT (-85.65606 41.94811)  ...     None       None  None

[5 rows x 9 columns]
```
would it be reasonable/feasible to request something like a `-resume` flag to pick back up where it hit the error?

**Comment by dragonejt** [comment]
We can probably just add the `ProtocolError` as an exception to retry on
