### ISSUE TITLE
fail on make requirements

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/street-view-green-view#53]
using Python 3.12.3

below error occurs when running either `make requirements` or `pip install -e .`

```
(.venv) ➜  street-view-green-view git:(main) make requirements
python3 -m pip install -U pip setuptools wheel
Requirement already satisfied: pip in ./.venv/lib/python3.12/site-packages (24.0)
Collecting setuptools
  Downloading setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
Collecting wheel
  Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Downloading setuptools-70.0.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.4/863.4 kB 16.7 MB/s eta 0:00:00
Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-70.0.0 wheel-0.43.0
python3 -m pip install -e .
Obtaining file:///Users/danbjoseph/GitHub/americanredcross/street-view-green-view
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting folium (from src==0.1.0)
  Downloading folium-0.17.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting geopandas (from src==0.1.0)
  Downloading geopandas-0.14.4-py3-none-any.whl.metadata (1.5 kB)
Collecting geopy (from src==0.1.0)
  Using cached geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting loguru (from src==0.1.0)
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting mapclassify (from src==0.1.0)
  Using cached mapclassify-2.6.1-py3-none-any.whl.metadata (2.6 kB)
Collecting matplotlib (from src==0.1.0)
  Downloading matplotlib-3.9.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (11 kB)
Collecting numpy (from src==0.1.0)
  Downloading numpy-2.0.0-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 3.3 MB/s eta 0:00:00
Collecting opencv-python (from src==0.1.0)
  Downloading opencv-python-4.10.0.84.tar.gz (95.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 MB 31.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Users/danbjoseph/GitHub/americanredcross/street-view-green-view/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/b6/3s_sztn53ls_77rt7bkhymy00000gn/T/pip-build-env-iut5akmj/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/b6/3s_sztn53ls_77rt7bkhymy00000gn/T/pip-build-env-iut5akmj/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/b6/3s_sztn53ls_77rt7bkhymy00000gn/T/pip-build-env-iut5akmj/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
make: *** [requirements] Error 1
```

**Comment by jayqi** [comment]
This looks like a bug with one of our dependencies, opencv-python: https://github.com/opencv/opencv-python/issues/988

**Comment by sibocw** [comment]
I had a similar issue on a different project. I was able to fix it (temporarily) by:
- `pip uninstall opencv-python` if one exists already
- Install opencv-python manually, removing the strict dependency on `setuptools==59.2.0`:
  - `git clone https://github.com/opencv/opencv-python.git` 
  - `cd opencv-python`
  - Remove the line `setuptools==59.2.0`
  - `pip install setuptools` to install an up-to-date version of setuptools manually (mine was 70.0.0)
  - `pip install .` to install opencv-python from the local copy
- Then continue installation as usual
